##############################################################################
#                                                                             #
#                         Parish Vitality                                     #
#                                                                             #
#                         Author: The Rev. Alistair So-Schoos                 #
#                                                                             #
#                                                                             #
#                                                                             #
# DESCRIPTION: Data processing, feature engineering, and Neuralnet analysis   #
#                                                                             #
#                                                                             #       
#                                                                             #
#                                                                             #
###############################################################################



#                           Clean global environment----

rm(list=ls())

#Load required libraries----

suppressMessages(library(dplyr))
suppressMessages(library(scales))
suppressMessages(library(tidyverse))
suppressMessages(library(DomoR))
suppressMessages(library(data.table))
suppressMessages(library(neuralnet))
suppressMessages(library(Boruta))


#Initiate Domo User Settings----

DomoR::init('company_name','enter_access_key')

sdir <- "~/Desktop/Parish_Vitality/"

#Load data from Domo----

#Read in parish training set----
parish_train <- DomoR::fetch('file_code')

#Checking the extent of NAs in this dataframe----
is.na(parish_train)

# list rows of data that have missing values----
#parish_train[!complete.cases(parish_train),]

# create new dataset without missing data
#newparish_train <- na.omit(parish_train)   #This can cause the df to have no rows.

#Data cleaning to ensure numerical data are recorded----

newparish_train <- parish_train %>%  
  mutate_at(vars(comyth17,
                 commad17,
                 commun17,
                 othact17,
                 worsh17,
                 wkdyworsh17,
                 easter17,
                 sundeu17,
                 wkdyeu17,
                 priveu17,
                 sunoff17,
                 wkdyof17,
                 adconf17,
                 adform17,
                 plcard17,
                 pledge17,
                 platpl17,
                 inves_17,
                 othinc17,
                 beques17,
                 norm_17,
                 diohlp17,
                 operev17,
                 capit_17,
                 endow17,
                 misrev17,
                 transr17,
                 nonop_17,
                 totrev17,
                 othexp17,
                 outexp17,
                 opexp17,
                 capexp17,
                 misexp17,
                 semexp17,
                 tranex17,
                 nonexp17,
                 totexp17,
                 cash17,
                 invest17,
                 memb17), 
            funs(as.numeric))

newparish_train <- newparish_train %>%  
  dplyr::mutate_at(vars(commad16,
                        commun16,
                        othact16,
                        worsh16,
                        wkdyworsh16,
                        weekly16,
                        easter16,
                        sundeu16,
                        wkdyeu16,
                        priveu16,
                        sunoff16,
                        wkdyof16,
                        marry16,
                        bury16,
                        adbapt16,
                        chbapt16,
                        adconf16,
                        chconf16,
                        receiv16,
                        ssenr16,
                        adeduc16,
                        adform16,
                        plcard16,
                        pledge16,
                        platpl16,
                        invest16,
                        othinc16,
                        beques16,
                        norm_16,
                        diohlp16,
                        operev16,
                        capit_16,
                        endow16,
                        misrev16,
                        transr16,
                        nonop_16,
                        totrev16,
                        todioc16,
                        othexp16,
                        outexp16,
                        opexp16,
                        capexp16,
                        misexp16,
                        semexp16,
                        tranex16,
                        nonexp16,
                        totexp16,
                        cash16,
                        invest16_1,
                        memb16), 
                   funs(as.numeric)) 

newparish_train <- newparish_train %>%  
  mutate_at(vars(gains13,
                 loss13,
                 othact13,
                 easter13,
                 sundeu13,
                 wkdyeu13,
                 priveu13,
                 sunoff13,
                 wkdyof13,
                 marry13,
                 bury13,
                 adbapt13,
                 chbapt13,
                 adconf13,
                 chconf13,
                 receiv13,
                 ssenr13,
                 adeduc13,
                 plcard13,
                 pledge13,
                 inves_13,
                 othinc13,
                 beques13,
                 norm_13,
                 diohlp13,
                 operev13,
                 capit_13,
                 endow13,
                 misrev13,
                 transr13,
                 nonop_13,
                 totrev13,
                 todioc13,
                 outexp13,
                 othexp13,
                 opexp13,
                 capexp13,
                 misexp13,
                 semexp13,
                 tranex13,
                 nonexp13,
                 totexp13,
                 cash13,
                 invest13), 
            funs(as.numeric))

newparish_train <- newparish_train %>%  
  mutate_at(vars(memlst15,
                 gains15,
                 loss15,
                 memb15,
                 comyth15,
                 commad15,
                 commun15,
                 othact15,
                 worsh15,
                 weekly15,
                 easter15,
                 sundeu15,
                 wkdyeu15,
                 priveu15,
                 sunoff15,
                 wkdyof15,
                 marry15,
                 bury15,
                 adbapt15,
                 chbapt15,
                 adconf15,
                 receiv15,
                 ssenr15,
                 adeduc15,
                 adform15,
                 plcard15,
                 pledge15,
                 platpl15,
                 othinc15,
                 inves_15,
                 beques15,
                 norm_15,
                 diohlp15,
                 operev15,
                 capit_15,
                 endow15,
                 misrev15,
                 transr15,
                 nonop_15,
                 totrev15,
                 todioc15,
                 othexp15,
                 opexp15,
                 outexp15,
                 capexp15,
                 misexp15,
                 semexp15,
                 tranex15,
                 nonexp15,
                 totexp15,
                 cash15,
                 invest15,
                 memb15), 
            funs(as.numeric))

newparish_train <- newparish_train %>%  
  mutate_at(vars(permembpledge10,
                 perasapledge10,
                 perunitpledge10,
                 easter10,
                 marry10,
                 bury10,
                 adbapt10,
                 chbapt10,
                 adconf10,
                 chconf10,
                 receiv10,
                 ssenr10,
                 adeduc10,
                 plcard10,
                 pledge10,
                 inves_10,
                 othinc10,
                 beques10,
                 norm_10,
                 diohlp10,
                 operev10,
                 capit_10,
                 endow10,
                 misrev10,
                 transr10,
                 nonop_10,
                 totrev10,
                 todioc10,
                 outexp10,
                 othexp10,
                 opexp10,
                 capexp10,
                 misexp10,
                 semexp10,
                 tranex10,
                 nonexp10,
                 totexp10,
                 cash10,
                 invest10), 
            funs(as.numeric)) %>% 
  mutate(., memb10 = round(pledge10/permembpledge10))


newparish_train <- newparish_train %>%  
  mutate_at(vars(memb09,
                 memlast09,
                 increase09,
                 decrease09,
                 worsh09,
                 platpl09,
                 commun09,
                 comyth09,
                 othact09,
                 pledge09,
                 easter09,
                 marry09,
                 bury09,
                 adbapt09,
                 chbapt09,
                 adconf09,
                 chconf09,
                 receiv09,
                 ssenr09,
                 adeduc09,
                 plcard09,
                 pledge09,
                 inves_09,
                 othinc09,
                 beques09,
                 norm_09,
                 diohlp09,
                 operev09,
                 capit_09,
                 endow09,
                 misrev09,
                 transr09,
                 nonop_09,
                 totrev09,
                 todioc09,
                 outexp09,
                 othexp09,
                 opexp09,
                 capexp09,
                 misexp09,
                 semexp09,
                 tranex09,
                 nonexp09,
                 totexp09,
                 cash09,
                 cash09a,
                 invest09), 
            funs(as.numeric))

newparish_train <- newparish_train %>%  
  mutate_at(vars(memb08,
                 worsh08,
                 platpl08,
                 commun08,
                 comyth08,
                 othact08,
                 pledge08,
                 easter08,
                 marry08,
                 bury08,
                 adbapt08,
                 chbapt08,
                 adconf08,
                 chconf08,
                 receiv08,
                 ssenr08,
                 adeduc08,
                 plcard08,
                 pledge08,
                 inves_08,
                 othinc08,
                 beques08,
                 norm_08,
                 diohlp08,
                 operev08,
                 capit_08,
                 endow08,
                 misrev08,
                 transr08,
                 nonop_08,
                 totrev08,
                 todioc08,
                 outexp08,
                 othexp08,
                 opexp08,
                 capexp08,
                 misexp08,
                 semexp08,
                 tranex08,
                 nonexp08,
                 totexp08,
                 cash08,
                 invest08), 
            funs(as.numeric))

newparish_train <- newparish_train %>%  
  mutate_at(vars(memb07,
                 worsh07,
                 confrm07,
                 bapt07,
                 sundeu07,
                 wkdyeu07,
                 priveu07,
                 sunoff07,
                 wkdyof07,
                 platpl07,
                 commun07,
                 comyth07,
                 othact07,
                 pledge07,
                 easter07,
                 marry07,
                 bury07,
                 adbapt07,
                 chbapt07,
                 adconf07,
                 chconf07,
                 receiv07,
                 ssenr07,
                 adeduc07,
                 plcard07,
                 inves_07,
                 othinc07,
                 beques07,
                 norm_07,
                 diohlp07,
                 operev07,
                 capit_07,
                 endow07,
                 misrev07,
                 transr07,
                 nonop_07,
                 totrev07,
                 todioc07,
                 outexp07,
                 othexp07,
                 opexp07,
                 capexp07,
                 misexp07,
                 semexp07,
                 tranex07,
                 nonexp07,
                 totexp07,
                 cash07,
                 invest07), 
            funs(as.numeric))

newparish_train <- newparish_train %>%  
  mutate_at(vars(memb06,
                 worsh06,
                 confrm06,
                 bapt06,
                 sundeu06,
                 wkdyeu06,
                 priveu06,
                 sunoff06,
                 wkdyof06,
                 platpl06,
                 pledge06,
                 commun06,
                 comyth06,
                 othact06,
                 pledge06,
                 easter06,
                 marry06,
                 bury06,
                 adbapt06,
                 chbapt06,
                 adconf06,
                 chconf06,
                 receiv06,
                 ssenr06,
                 adeduc06,
                 plcard06,
                 inves_06,
                 othinc06,
                 beques06,
                 norm_06,
                 diohlp06,
                 operev06,
                 capit_06,
                 endow06,
                 misrev06,
                 transr06,
                 nonop_06,
                 totrev06,
                 todioc06,
                 outexp06,
                 othexp06,
                 opexp06,
                 capexp06,
                 misexp06,
                 semexp06,
                 tranex06,
                 nonexp06,
                 totexp06,
                 cash06,
                 invest06), 
            funs(as.numeric))

newparish_train <- newparish_train %>%  
  mutate_at(vars(memb05,
                 worsh05,
                 worsh05a,
                 confrm05,
                 bapt05,
                 sundeu05,
                 wkdyeu05,
                 priveu05,
                 sunoff05,
                 wkdyof05,
                 platpl05,
                 pledge05,
                 commun05,
                 comyth05,
                 othact05,
                 pledge05,
                 easter05,
                 marry05,
                 adbapt05,
                 chbapt05,
                 adconf05,
                 chconf05,
                 receiv05,
                 ssenr05,
                 adeduc05,
                 plcard05,
                 inves_05,
                 othinc05,
                 beques05,
                 norm_05,
                 diohlp05,
                 operev05,
                 capit_05,
                 endow05,
                 misrev05,
                 transr05,
                 nonop_05,
                 totrev05,
                 todioc05,
                 outexp05,
                 othexp05,
                 opexp05,
                 capexp05,
                 misexp05,
                 tranex05,
                 nonexp05,
                 totexp05,
                 cash05,
                 invest05,
                 closed_year,
                 memb16,
                 memb12,
                 memb04,
                 memb03,
                 memb02,
                 memb01,
                 memb00,
                 memb13,
                 TSEGNUM,
                 TLIFECODE,
                 TADULTBASE,
                 GEOID,
                 othact10
  ), 
  funs(as.numeric)) %>% 
  mutate(., close_status = 0 ) %>% 
  mutate(., close_status = ifelse(closed_indicator == 'Y', 1, close_status)) %>% 
  mutate(., close_status = ifelse(closed_indicator == 'N', 0, close_status)) %>% 
  mutate(., close_status = ifelse(closed_indicator == 'NA' & closed == 'Open', 0, close_status)) %>% 
  mutate(., close_status = ifelse(closed_indicator == 'NA' & closed == 'Closed', 1, close_status)) %>% 
  select(.,memb05,
         worsh05,
         worsh05a,
         confrm05,
         bapt05,
         sundeu05,
         wkdyeu05,
         priveu05,
         sunoff05,
         wkdyof05,
         platpl05,
         pledge05,
         commun05,
         comyth05,
         othact05,
         pledge05,
         easter05,
         marry05,
         adbapt05,
         chbapt05,
         adconf05,
         chconf05,
         receiv05,
         ssenr05,
         adeduc05,
         plcard05,
         inves_05,
         othinc05,
         beques05,
         norm_05,
         diohlp05,
         operev05,
         capit_05,
         endow05,
         misrev05,
         transr05,
         nonop_05,
         totrev05,
         todioc05,
         outexp05,
         othexp05,
         opexp05,
         capexp05,
         misexp05,
         tranex05,
         nonexp05,
         totexp05,
         cash05,
         invest05,
         closed_year,
         memb16,
         memb12,
         memb04,
         memb03,
         memb02,
         memb01,
         memb00,
         memb13,
         TSEGNUM,
         TLIFECODE,
         memb06,
         worsh06,
         confrm06,
         bapt06,
         sundeu06,
         wkdyeu06,
         priveu06,
         sunoff06,
         wkdyof06,
         platpl06,
         pledge06,
         commun06,
         comyth06,
         othact06,
         pledge06,
         easter06,
         marry06,
         bury06,
         adbapt06,
         chbapt06,
         adconf06,
         chconf06,
         receiv06,
         ssenr06,
         adeduc06,
         plcard06,
         inves_06,
         othinc06,
         beques06,
         norm_06,
         diohlp06,
         operev06,
         capit_06,
         endow06,
         misrev06,
         transr06,
         nonop_06,
         totrev06,
         todioc06,
         outexp06,
         othexp06,
         opexp06,
         capexp06,
         misexp06,
         semexp06,
         tranex06,
         nonexp06,
         totexp06,
         cash06,
         invest06,
         memb07,
         worsh07,
         confrm07,
         bapt07,
         sundeu07,
         wkdyeu07,
         priveu07,
         sunoff07,
         wkdyof07,
         platpl07,
         commun07,
         comyth07,
         othact07,
         pledge07,
         easter07,
         marry07,
         bury07,
         adbapt07,
         chbapt07,
         adconf07,
         chconf07,
         receiv07,
         ssenr07,
         adeduc07,
         plcard07,
         inves_07,
         othinc07,
         beques07,
         norm_07,
         diohlp07,
         operev07,
         capit_07,
         endow07,
         misrev07,
         transr07,
         nonop_07,
         totrev07,
         todioc07,
         outexp07,
         othexp07,
         opexp07,
         capexp07,
         misexp07,
         semexp07,
         tranex07,
         nonexp07,
         totexp07,
         cash07,
         invest07,
         memb08,
         worsh08,
         platpl08,
         commun08,
         comyth08,
         othact08,
         pledge08,
         easter08,
         marry08,
         bury08,
         adbapt08,
         chbapt08,
         adconf08,
         chconf08,
         receiv08,
         ssenr08,
         adeduc08,
         plcard08,
         pledge08,
         inves_08,
         othinc08,
         beques08,
         norm_08,
         diohlp08,
         operev08,
         capit_08,
         endow08,
         misrev08,
         transr08,
         nonop_08,
         totrev08,
         todioc08,
         outexp08,
         othexp08,
         opexp08,
         capexp08,
         misexp08,
         semexp08,
         tranex08,
         nonexp08,
         totexp08,
         cash08,
         invest08,
         memb09,
         memlast09,
         increase09,
         decrease09,
         worsh09,
         platpl09,
         commun09,
         comyth09,
         othact09,
         pledge09,
         easter09,
         marry09,
         bury09,
         adbapt09,
         chbapt09,
         adconf09,
         chconf09,
         receiv09,
         ssenr09,
         adeduc09,
         plcard09,
         pledge09,
         inves_09,
         othinc09,
         beques09,
         norm_09,
         diohlp09,
         operev09,
         capit_09,
         endow09,
         misrev09,
         transr09,
         nonop_09,
         totrev09,
         todioc09,
         outexp09,
         othexp09,
         opexp09,
         capexp09,
         misexp09,
         semexp09,
         tranex09,
         nonexp09,
         totexp09,
         cash09,
         cash09a,
         invest09,
         permembpledge10,
         perasapledge10,
         perunitpledge10,
         easter10,
         marry10,
         bury10,
         adbapt10,
         chbapt10,
         adconf10,
         chconf10,
         receiv10,
         ssenr10,
         adeduc10,
         plcard10,
         pledge10,
         inves_10,
         othinc10,
         beques10,
         norm_10,
         diohlp10,
         operev10,
         capit_10,
         endow10,
         misrev10,
         transr10,
         nonop_10,
         totrev10,
         todioc10,
         outexp10,
         othexp10,
         opexp10,
         capexp10,
         misexp10,
         semexp10,
         tranex10,
         nonexp10,
         totexp10,
         cash10,
         invest10,
         memlst15,
         gains15,
         loss15,
         memb15,
         comyth15,
         commad15,
         commun15,
         othact15,
         worsh15,
         weekly15,
         easter15,
         sundeu15,
         wkdyeu15,
         priveu15,
         sunoff15,
         wkdyof15,
         marry15,
         bury15,
         adbapt15,
         chbapt15,
         adconf15,
         receiv15,
         ssenr15,
         adeduc15,
         adform15,
         plcard15,
         pledge15,
         platpl15,
         othinc15,
         inves_15,
         beques15,
         norm_15,
         diohlp15,
         operev15,
         capit_15,
         endow15,
         misrev15,
         transr15,
         nonop_15,
         totrev15,
         todioc15,
         othexp15,
         opexp15,
         outexp15,
         capexp15,
         misexp15,
         semexp15,
         tranex15,
         nonexp15,
         totexp15,
         cash15,
         invest15,
         memb15,
         gains13,
         loss13,
         othact13,
         easter13,
         sundeu13,
         wkdyeu13,
         priveu13,
         sunoff13,
         wkdyof13,
         marry13,
         bury13,
         adbapt13,
         chbapt13,
         adconf13,
         chconf13,
         receiv13,
         ssenr13,
         adeduc13,
         plcard13,
         pledge13,
         inves_13,
         othinc13,
         beques13,
         norm_13,
         diohlp13,
         operev13,
         capit_13,
         endow13,
         misrev13,
         transr13,
         nonop_13,
         totrev13,
         todioc13,
         outexp13,
         othexp13,
         opexp13,
         capexp13,
         misexp13,
         semexp13,
         tranex13,
         nonexp13,
         totexp13,
         cash13,
         invest13,
         commad16,
         commun16,
         othact16,
         worsh16,
         wkdyworsh16,
         weekly16,
         easter16,
         sundeu16,
         wkdyeu16,
         priveu16,
         sunoff16,
         wkdyof16,
         marry16,
         bury16,
         adbapt16,
         chbapt16,
         adconf16,
         chconf16,
         receiv16,
         ssenr16,
         adeduc16,
         adform16,
         plcard16,
         pledge16,
         platpl16,
         invest16,
         othinc16,
         beques16,
         norm_16,
         diohlp16,
         operev16,
         capit_16,
         endow16,
         misrev16,
         transr16,
         nonop_16,
         totrev16,
         todioc16,
         othexp16,
         outexp16,
         opexp16,
         capexp16,
         misexp16,
         semexp16,
         tranex16,
         nonexp16,
         totexp16,
         cash16,
         invest16_1,
         memb16,
         comyth17,
         commad17,
         commun17,
         othact17,
         chconf17,
         worsh17,
         wkdyworsh17,
         easter17,
         sundeu17,
         wkdyeu17,
         priveu17,
         sunoff17,
         wkdyof17,
         adconf17,
         chconf17,                   
         adform17,
         plcard17,
         pledge17,
         platpl17,
         inves_17,
         othinc17,
         beques17,
         norm_17,
         diohlp17,
         operev17,
         capit_17,
         endow17,
         misrev17,
         transr17,
         nonop_17,
         totrev17,
         othexp17,
         outexp17,
         opexp17,
         capexp17,
         misexp17,
         semexp17,
         tranex17,
         nonexp17,
         totexp17,
         cash17,
         invest17,
         memb17,
         close_status,
         GEOID,
         edw_org_id,
         clerics_employed,
         TADULTBASE,
         scapacity,
         ssenr17,
         bury17,
         adbapt17,
         chbapt17,
         othact10
  ) %>% 
  replace(is.na(.), 0)

#newparish_train <- newparish_train %>% 
#select(., closed_indicator, clerics_employed, pledge17, pledge16, pledge15, memb17, memb16, memb15, TLIFECODE, TSEGNUM, easter17, easter16, easter15, invest17, invest16, invest15)

#Conduct a test for feature imnportance----
# Perform Boruta search

boruta_output <- Boruta(close_status ~ ., data=na.omit(newparish_train), doTrace=3)  

names(boruta_output)  #Shows what's in the output file.

# Get significant variables including tentatives
boruta_signif <- getSelectedAttributes(boruta_output, withTentative = TRUE)
print(boruta_signif)  

# Do a tentative rough fix----
roughFixMod <- TentativeRoughFix(boruta_output)
boruta_signif <- getSelectedAttributes(roughFixMod)
print(boruta_signif)

# Plot variable importance
plot(boruta_output, cex.axis=.7, las=2, xlab="", main="Variable Importance in Training Set")  

#Read in parish test set----
parish_test <- DomoR::fetch('file_code')

#Checking the extent of NAs in this dataframe----
is.na(parish_test)

# list rows of data that have missing values----
#parish_test[!complete.cases(parish_test),]

# create new dataset without missing data
#newparish_test <- na.omit(parish_test) 

#Data cleaning to ensure numerical data are used----

newparish_test <- parish_test %>%  
  mutate_at(vars(comyth17,
                 commad17,
                 commun17,
                 othact17,
                 worsh17,
                 wkdyworsh17,
                 easter17,
                 sundeu17,
                 wkdyeu17,
                 priveu17,
                 sunoff17,
                 wkdyof17,
                 adconf17,
                 adform17,
                 plcard17,
                 pledge17,
                 platpl17,
                 inves_17,
                 othinc17,
                 beques17,
                 norm_17,
                 diohlp17,
                 operev17,
                 capit_17,
                 endow17,
                 misrev17,
                 transr17,
                 nonop_17,
                 totrev17,
                 othexp17,
                 outexp17,
                 opexp17,
                 capexp17,
                 misexp17,
                 semexp17,
                 tranex17,
                 nonexp17,
                 totexp17,
                 cash17,
                 invest17,
                 memb17), 
            funs(as.numeric))

newparish_test <- newparish_test %>%  
  dplyr::mutate_at(vars(commad16,
                        commun16,
                        othact16,
                        worsh16,
                        wkdyworsh16,
                        weekly16,
                        easter16,
                        sundeu16,
                        wkdyeu16,
                        priveu16,
                        sunoff16,
                        wkdyof16,
                        marry16,
                        bury16,
                        adbapt16,
                        chbapt16,
                        adconf16,
                        chconf16,
                        receiv16,
                        ssenr16,
                        adeduc16,
                        adform16,
                        plcard16,
                        pledge16,
                        platpl16,
                        invest16,
                        othinc16,
                        beques16,
                        norm_16,
                        diohlp16,
                        operev16,
                        capit_16,
                        endow16,
                        misrev16,
                        transr16,
                        nonop_16,
                        totrev16,
                        todioc16,
                        othexp16,
                        outexp16,
                        opexp16,
                        capexp16,
                        misexp16,
                        semexp16,
                        tranex16,
                        nonexp16,
                        totexp16,
                        cash16,
                        invest16_1,
                        memb16), 
                   funs(as.numeric)) 

newparish_test <- newparish_test %>%  
  mutate_at(vars(gains13,
                 loss13,
                 othact13,
                 easter13,
                 sundeu13,
                 wkdyeu13,
                 priveu13,
                 sunoff13,
                 wkdyof13,
                 marry13,
                 bury13,
                 adbapt13,
                 chbapt13,
                 adconf13,
                 chconf13,
                 receiv13,
                 ssenr13,
                 adeduc13,
                 plcard13,
                 pledge13,
                 inves_13,
                 othinc13,
                 beques13,
                 norm_13,
                 diohlp13,
                 operev13,
                 capit_13,
                 endow13,
                 misrev13,
                 transr13,
                 nonop_13,
                 totrev13,
                 todioc13,
                 outexp13,
                 othexp13,
                 opexp13,
                 capexp13,
                 misexp13,
                 semexp13,
                 tranex13,
                 nonexp13,
                 totexp13,
                 cash13,
                 invest13), 
            funs(as.numeric))

newparish_test <- newparish_test %>%  
  mutate_at(vars(memlst15,
                 gains15,
                 loss15,
                 memb15,
                 comyth15,
                 commad15,
                 commun15,
                 othact15,
                 worsh15,
                 weekly15,
                 easter15,
                 sundeu15,
                 wkdyeu15,
                 priveu15,
                 sunoff15,
                 wkdyof15,
                 marry15,
                 bury15,
                 adbapt15,
                 chbapt15,
                 adconf15,
                 receiv15,
                 ssenr15,
                 adeduc15,
                 adform15,
                 plcard15,
                 pledge15,
                 platpl15,
                 othinc15,
                 inves_15,
                 beques15,
                 norm_15,
                 diohlp15,
                 operev15,
                 capit_15,
                 endow15,
                 misrev15,
                 transr15,
                 nonop_15,
                 totrev15,
                 todioc15,
                 othexp15,
                 opexp15,
                 outexp15,
                 capexp15,
                 misexp15,
                 semexp15,
                 tranex15,
                 nonexp15,
                 totexp15,
                 cash15,
                 invest15,
                 memb15), 
            funs(as.numeric))

newparish_test <- newparish_test %>%  
  mutate_at(vars(permembpledge10,
                 perasapledge10,
                 perunitpledge10,
                 easter10,
                 marry10,
                 bury10,
                 adbapt10,
                 chbapt10,
                 adconf10,
                 chconf10,
                 receiv10,
                 ssenr10,
                 adeduc10,
                 plcard10,
                 pledge10,
                 inves_10,
                 othinc10,
                 beques10,
                 norm_10,
                 diohlp10,
                 operev10,
                 capit_10,
                 endow10,
                 misrev10,
                 transr10,
                 nonop_10,
                 totrev10,
                 todioc10,
                 outexp10,
                 othexp10,
                 opexp10,
                 capexp10,
                 misexp10,
                 semexp10,
                 tranex10,
                 nonexp10,
                 totexp10,
                 cash10,
                 invest10), 
            funs(as.numeric)) %>% 
  mutate(., memb10 = round(pledge10/permembpledge10))


newparish_test <- newparish_test %>%  
  mutate_at(vars(memb09,
                 memlast09,
                 increase09,
                 decrease09,
                 worsh09,
                 platpl09,
                 commun09,
                 comyth09,
                 othact09,
                 pledge09,
                 easter09,
                 marry09,
                 bury09,
                 adbapt09,
                 chbapt09,
                 adconf09,
                 chconf09,
                 receiv09,
                 ssenr09,
                 adeduc09,
                 plcard09,
                 pledge09,
                 inves_09,
                 othinc09,
                 beques09,
                 norm_09,
                 diohlp09,
                 operev09,
                 capit_09,
                 endow09,
                 misrev09,
                 transr09,
                 nonop_09,
                 totrev09,
                 todioc09,
                 outexp09,
                 othexp09,
                 opexp09,
                 capexp09,
                 misexp09,
                 semexp09,
                 tranex09,
                 nonexp09,
                 totexp09,
                 cash09,
                 cash09a,
                 invest09), 
            funs(as.numeric))

newparish_test <- newparish_test %>%  
  mutate_at(vars(memb08,
                 worsh08,
                 platpl08,
                 commun08,
                 comyth08,
                 othact08,
                 pledge08,
                 easter08,
                 marry08,
                 bury08,
                 adbapt08,
                 chbapt08,
                 adconf08,
                 chconf08,
                 receiv08,
                 ssenr08,
                 adeduc08,
                 plcard08,
                 pledge08,
                 inves_08,
                 othinc08,
                 beques08,
                 norm_08,
                 diohlp08,
                 operev08,
                 capit_08,
                 endow08,
                 misrev08,
                 transr08,
                 nonop_08,
                 totrev08,
                 todioc08,
                 outexp08,
                 othexp08,
                 opexp08,
                 capexp08,
                 misexp08,
                 semexp08,
                 tranex08,
                 nonexp08,
                 totexp08,
                 cash08,
                 invest08), 
            funs(as.numeric))

newparish_test <- newparish_test %>%  
  mutate_at(vars(memb07,
                 worsh07,
                 confrm07,
                 bapt07,
                 sundeu07,
                 wkdyeu07,
                 priveu07,
                 sunoff07,
                 wkdyof07,
                 platpl07,
                 commun07,
                 comyth07,
                 othact07,
                 pledge07,
                 easter07,
                 marry07,
                 bury07,
                 adbapt07,
                 chbapt07,
                 adconf07,
                 chconf07,
                 receiv07,
                 ssenr07,
                 adeduc07,
                 plcard07,
                 inves_07,
                 othinc07,
                 beques07,
                 norm_07,
                 diohlp07,
                 operev07,
                 capit_07,
                 endow07,
                 misrev07,
                 transr07,
                 nonop_07,
                 totrev07,
                 todioc07,
                 outexp07,
                 othexp07,
                 opexp07,
                 capexp07,
                 misexp07,
                 semexp07,
                 tranex07,
                 nonexp07,
                 totexp07,
                 cash07,
                 invest07), 
            funs(as.numeric))

newparish_test <- newparish_test %>%  
  mutate_at(vars(memb06,
                 worsh06,
                 confrm06,
                 bapt06,
                 sundeu06,
                 wkdyeu06,
                 priveu06,
                 sunoff06,
                 wkdyof06,
                 platpl06,
                 pledge06,
                 commun06,
                 comyth06,
                 othact06,
                 pledge06,
                 easter06,
                 marry06,
                 bury06,
                 adbapt06,
                 chbapt06,
                 adconf06,
                 chconf06,
                 receiv06,
                 ssenr06,
                 adeduc06,
                 plcard06,
                 inves_06,
                 othinc06,
                 beques06,
                 norm_06,
                 diohlp06,
                 operev06,
                 capit_06,
                 endow06,
                 misrev06,
                 transr06,
                 nonop_06,
                 totrev06,
                 todioc06,
                 outexp06,
                 othexp06,
                 opexp06,
                 capexp06,
                 misexp06,
                 semexp06,
                 tranex06,
                 nonexp06,
                 totexp06,
                 cash06,
                 invest06), 
            funs(as.numeric))

#Cleaning and selecting columns----
newparish_test <- newparish_test %>%  
  mutate_at(vars(memb05,
                 worsh05,
                 worsh05a,
                 confrm05,
                 bapt05,
                 sundeu05,
                 wkdyeu05,
                 priveu05,
                 sunoff05,
                 wkdyof05,
                 platpl05,
                 pledge05,
                 commun05,
                 comyth05,
                 othact05,
                 pledge05,
                 easter05,
                 marry05,
                 adbapt05,
                 chbapt05,
                 adconf05,
                 chconf05,
                 receiv05,
                 ssenr05,
                 adeduc05,
                 plcard05,
                 inves_05,
                 othinc05,
                 beques05,
                 norm_05,
                 diohlp05,
                 operev05,
                 capit_05,
                 endow05,
                 misrev05,
                 transr05,
                 nonop_05,
                 totrev05,
                 todioc05,
                 outexp05,
                 othexp05,
                 opexp05,
                 capexp05,
                 misexp05,
                 tranex05,
                 nonexp05,
                 totexp05,
                 cash05,
                 invest05,
                 closed_year,
                 memb16,
                 memb12,
                 memb04,
                 memb03,
                 memb02,
                 memb01,
                 memb00,
                 memb13,
                 TSEGNUM,
                 TLIFECODE,
                 TADULTBASE,
                 GEOID,
                 othact10
  ), 
  funs(as.numeric)) %>% 
  mutate(., close_status = 0 ) %>% 
  mutate(., close_status = ifelse(closed_indicator == 'Y', 1, close_status)) %>% 
  mutate(., close_status = ifelse(closed_indicator == 'N', 0, close_status)) %>% 
  mutate(., close_status = ifelse(closed_indicator == 'NA' & closed == 'Open', 0, close_status)) %>% 
  mutate(., close_status = ifelse(closed_indicator == 'NA' & closed == 'Closed', 1, close_status)) %>% 
  select(.,memb05,
         worsh05,
         worsh05a,
         confrm05,
         bapt05,
         sundeu05,
         wkdyeu05,
         priveu05,
         sunoff05,
         wkdyof05,
         platpl05,
         pledge05,
         commun05,
         comyth05,
         othact05,
         pledge05,
         easter05,
         marry05,
         adbapt05,
         chbapt05,
         adconf05,
         chconf05,
         receiv05,
         ssenr05,
         adeduc05,
         plcard05,
         inves_05,
         othinc05,
         beques05,
         norm_05,
         diohlp05,
         operev05,
         capit_05,
         endow05,
         misrev05,
         transr05,
         nonop_05,
         totrev05,
         todioc05,
         outexp05,
         othexp05,
         opexp05,
         capexp05,
         misexp05,
         tranex05,
         nonexp05,
         totexp05,
         cash05,
         invest05,
         closed_year,
         memb16,
         memb12,
         memb04,
         memb03,
         memb02,
         memb01,
         memb00,
         memb13,
         TSEGNUM,
         TLIFECODE,
         memb06,
         worsh06,
         confrm06,
         bapt06,
         sundeu06,
         wkdyeu06,
         priveu06,
         sunoff06,
         wkdyof06,
         platpl06,
         pledge06,
         commun06,
         comyth06,
         othact06,
         pledge06,
         easter06,
         marry06,
         bury06,
         adbapt06,
         chbapt06,
         adconf06,
         chconf06,
         receiv06,
         ssenr06,
         adeduc06,
         plcard06,
         inves_06,
         othinc06,
         beques06,
         norm_06,
         diohlp06,
         operev06,
         capit_06,
         endow06,
         misrev06,
         transr06,
         nonop_06,
         totrev06,
         todioc06,
         outexp06,
         othexp06,
         opexp06,
         capexp06,
         misexp06,
         semexp06,
         tranex06,
         nonexp06,
         totexp06,
         cash06,
         invest06,
         memb07,
         worsh07,
         confrm07,
         bapt07,
         sundeu07,
         wkdyeu07,
         priveu07,
         sunoff07,
         wkdyof07,
         platpl07,
         commun07,
         comyth07,
         othact07,
         pledge07,
         easter07,
         marry07,
         bury07,
         adbapt07,
         chbapt07,
         adconf07,
         chconf07,
         receiv07,
         ssenr07,
         adeduc07,
         plcard07,
         inves_07,
         othinc07,
         beques07,
         norm_07,
         diohlp07,
         operev07,
         capit_07,
         endow07,
         misrev07,
         transr07,
         nonop_07,
         totrev07,
         todioc07,
         outexp07,
         othexp07,
         opexp07,
         capexp07,
         misexp07,
         semexp07,
         tranex07,
         nonexp07,
         totexp07,
         cash07,
         invest07,
         memb08,
         worsh08,
         platpl08,
         commun08,
         comyth08,
         othact08,
         pledge08,
         easter08,
         marry08,
         bury08,
         adbapt08,
         chbapt08,
         adconf08,
         chconf08,
         receiv08,
         ssenr08,
         adeduc08,
         plcard08,
         pledge08,
         inves_08,
         othinc08,
         beques08,
         norm_08,
         diohlp08,
         operev08,
         capit_08,
         endow08,
         misrev08,
         transr08,
         nonop_08,
         totrev08,
         todioc08,
         outexp08,
         othexp08,
         opexp08,
         capexp08,
         misexp08,
         semexp08,
         tranex08,
         nonexp08,
         totexp08,
         cash08,
         invest08,
         memb09,
         memlast09,
         increase09,
         decrease09,
         worsh09,
         platpl09,
         commun09,
         comyth09,
         othact09,
         pledge09,
         easter09,
         marry09,
         bury09,
         adbapt09,
         chbapt09,
         adconf09,
         chconf09,
         receiv09,
         ssenr09,
         adeduc09,
         plcard09,
         pledge09,
         inves_09,
         othinc09,
         beques09,
         norm_09,
         diohlp09,
         operev09,
         capit_09,
         endow09,
         misrev09,
         transr09,
         nonop_09,
         totrev09,
         todioc09,
         outexp09,
         othexp09,
         opexp09,
         capexp09,
         misexp09,
         semexp09,
         tranex09,
         nonexp09,
         totexp09,
         cash09,
         cash09a,
         invest09,
         permembpledge10,
         perasapledge10,
         perunitpledge10,
         easter10,
         marry10,
         bury10,
         adbapt10,
         chbapt10,
         adconf10,
         chconf10,
         receiv10,
         ssenr10,
         adeduc10,
         plcard10,
         pledge10,
         inves_10,
         othinc10,
         beques10,
         norm_10,
         diohlp10,
         operev10,
         capit_10,
         endow10,
         misrev10,
         transr10,
         nonop_10,
         totrev10,
         todioc10,
         outexp10,
         othexp10,
         opexp10,
         capexp10,
         misexp10,
         semexp10,
         tranex10,
         nonexp10,
         totexp10,
         cash10,
         invest10,
         memlst15,
         gains15,
         loss15,
         memb15,
         comyth15,
         commad15,
         commun15,
         othact15,
         worsh15,
         weekly15,
         easter15,
         sundeu15,
         wkdyeu15,
         priveu15,
         sunoff15,
         wkdyof15,
         marry15,
         bury15,
         adbapt15,
         chbapt15,
         adconf15,
         receiv15,
         ssenr15,
         adeduc15,
         adform15,
         plcard15,
         pledge15,
         platpl15,
         othinc15,
         inves_15,
         beques15,
         norm_15,
         diohlp15,
         operev15,
         capit_15,
         endow15,
         misrev15,
         transr15,
         nonop_15,
         totrev15,
         todioc15,
         othexp15,
         opexp15,
         outexp15,
         capexp15,
         misexp15,
         semexp15,
         tranex15,
         nonexp15,
         totexp15,
         cash15,
         invest15,
         memb15,
         gains13,
         loss13,
         othact13,
         easter13,
         sundeu13,
         wkdyeu13,
         priveu13,
         sunoff13,
         wkdyof13,
         marry13,
         bury13,
         adbapt13,
         chbapt13,
         adconf13,
         chconf13,
         receiv13,
         ssenr13,
         adeduc13,
         plcard13,
         pledge13,
         inves_13,
         othinc13,
         beques13,
         norm_13,
         diohlp13,
         operev13,
         capit_13,
         endow13,
         misrev13,
         transr13,
         nonop_13,
         totrev13,
         todioc13,
         outexp13,
         othexp13,
         opexp13,
         capexp13,
         misexp13,
         semexp13,
         tranex13,
         nonexp13,
         totexp13,
         cash13,
         invest13,
         commad16,
         commun16,
         othact16,
         worsh16,
         wkdyworsh16,
         weekly16,
         easter16,
         sundeu16,
         wkdyeu16,
         priveu16,
         sunoff16,
         wkdyof16,
         marry16,
         bury16,
         adbapt16,
         chbapt16,
         adconf16,
         chconf16,
         receiv16,
         ssenr16,
         adeduc16,
         adform16,
         plcard16,
         pledge16,
         platpl16,
         invest16,
         othinc16,
         beques16,
         norm_16,
         diohlp16,
         operev16,
         capit_16,
         endow16,
         misrev16,
         transr16,
         nonop_16,
         totrev16,
         todioc16,
         othexp16,
         outexp16,
         opexp16,
         capexp16,
         misexp16,
         semexp16,
         tranex16,
         nonexp16,
         totexp16,
         cash16,
         invest16_1,
         memb16,
         comyth17,
         commad17,
         commun17,
         othact17,
         chconf17,
         worsh17,
         wkdyworsh17,
         easter17,
         sundeu17,
         wkdyeu17,
         priveu17,
         sunoff17,
         wkdyof17,
         adconf17,
         chconf17,                   
         adform17,
         plcard17,
         pledge17,
         platpl17,
         inves_17,
         othinc17,
         beques17,
         norm_17,
         diohlp17,
         operev17,
         capit_17,
         endow17,
         misrev17,
         transr17,
         nonop_17,
         totrev17,
         othexp17,
         outexp17,
         opexp17,
         capexp17,
         misexp17,
         semexp17,
         tranex17,
         nonexp17,
         totexp17,
         cash17,
         invest17,
         memb17,
         close_status,
         GEOID,
         edw_org_id,
         clerics_employed,
         TADULTBASE,
         scapacity,
         ssenr17,
         bury17,
         adbapt17,
         chbapt17,
         othact10
  ) %>% 
  replace(is.na(.), 0)


#Conduct a test for feature imnportance----
# Perform Boruta search

boruta_output2 <- Boruta(close_status ~ ., data=na.omit(newparish_test), doTrace=3)  

names(boruta_output2)  #Shows what's in the output file.

# Get significant variables including tentatives
boruta_signif2 <- getSelectedAttributes(boruta_output2, withTentative = TRUE)
print(boruta_signif2)  

# Do a tentative rough fix----
roughFixMod2 <- TentativeRoughFix(boruta_output2)
boruta_signif2 <- getSelectedAttributes(roughFixMod2)
print(boruta_signif2)

# Plot variable importance
plot(boruta_output2, cex.axis=.7, las=2, xlab="", main="Variable Importance in Test Set")  


#Append Training and Test Sets to check for feature importance----

parish_combo <- rbind(newparish_train, newparish_test)

#Conduct a test for feature imnportance----
# Perform Boruta search

boruta_output3 <- Boruta(close_status ~ ., data=na.omit(parish_combo), doTrace=3)  

names(boruta_output3)  #Shows what's in the output file.

# Get significant variables including tentatives
boruta_signif3 <- getSelectedAttributes(boruta_output3, withTentative = TRUE)
print(boruta_signif3)  

# Do a tentative rough fix----
roughFixMod3 <- TentativeRoughFix(boruta_output3)
boruta_signif3 <- getSelectedAttributes(roughFixMod3)
print(boruta_signif3)

# Plot variable importance
plot(boruta_output3, cex.axis=.7, las=2, xlab="", main="Variable Importance in Combined Set")  

#Engineer derived features----



#Feature of Attendance

parish_combo$attendance17 <- parish_combo$worsh17 

parish_combo$attendance16 <- parish_combo$worsh16 

parish_combo$attendance15 <- parish_combo$worsh15 

parish_combo$attendance09 <- parish_combo$worsh09     

parish_combo$attendance08 <- parish_combo$worsh08   

parish_combo$attendance07 <- parish_combo$worsh07 

parish_combo$attendance05 <- parish_combo$worsh05 

#Feature of all Eucharists

parish_combo$all_EU17 <- parish_combo$sundeu17 + parish_combo$wkdyeu17 + parish_combo$priveu17

parish_combo$all_EU16 <- parish_combo$sundeu16 + parish_combo$wkdyeu16 + parish_combo$priveu16

parish_combo$all_EU15 <- parish_combo$sundeu15 + parish_combo$wkdyeu15 + parish_combo$priveu15

parish_combo$all_EU07 <- parish_combo$sundeu07 + parish_combo$wkdyeu07 + parish_combo$priveu07

parish_combo$all_EU06 <- parish_combo$sundeu06 + parish_combo$wkdyeu06 + parish_combo$priveu06

parish_combo$all_EU05 <- parish_combo$sundeu05 + parish_combo$wkdyeu05 + parish_combo$priveu05


#Create CSV for analysis in another R script----

write.csv(parish_combo, file=paste0(sdir, "parish_combo_vita.csv"))

#Select columns for neuralnet analysis----


parish_training <- newparish_train %>% 
  mutate(., close_status = NA ) %>% 
  mutate(., close_status = ifelse(closed_indicator == 'Y', 1, close_status)) %>% 
  mutate(., close_status = ifelse(closed_indicator == 'N', 0, close_status)) %>% 
  select(., pledge17, totrev17, endow17, totexp17, commun17, ssenr17, worsh17, easter17,
         pledge16, totrev16, totexp16, commun16, ssenr16, worsh16, easter16,
         pledge15, totrev15, totexp15, commun15, ssenr16, worsh15, easter15,
         pledge13, totrev13, totexp13, memb13, ssenr13, easter13,
         pledge10, totrev10, totexp10, memb10, ssenr10, easter10, 
         pledge09, totrev09, totexp09, memb09, ssenr09, easter09, worsh09,
         pledge08, totrev08, totexp08, memb08, ssenr08, easter08, worsh08,
         pledge07, totrev07, totexp07, memb07, ssenr07, easter07, worsh07,
         pledge06, totrev06, totexp06, memb06, ssenr06, easter06, worsh06,
         pledge05, totrev05, totexp05, memb05, ssenr05, easter05, worsh05,
         TSEGNUM, TLIFECODE, close_status
  )

parish_testing <- newparish_test %>% 
  mutate(., close_status = NA ) %>% 
  mutate(., close_status = ifelse(closed_indicator == 'Y', 1, close_status)) %>% 
  mutate(., close_status = ifelse(closed_indicator == 'N', 0, close_status)) %>% 
  select(., pledge17, totrev17, endow17, totexp17, commun17, ssenr17, worsh17, easter17,
         pledge16, totrev16, totexp16, commun16, ssenr16, worsh16, easter16,
         pledge15, totrev15, totexp15, commun15, ssenr16, worsh15, easter15,
         pledge13, totrev13, totexp13, memb13, ssenr13, easter13,
         pledge10, totrev10, totexp10, memb10, ssenr10, easter10, 
         pledge09, totrev09, totexp09, memb09, ssenr09, easter09, worsh09,
         pledge08, totrev08, totexp08, memb08, ssenr08, easter08, worsh08,
         pledge07, totrev07, totexp07, memb07, ssenr07, easter07, worsh07,
         pledge06, totrev06, totexp06, memb06, ssenr06, easter06, worsh06,
         pledge05, totrev05, totexp05, memb05, ssenr05, easter05, worsh05,
         TSEGNUM, TLIFECODE, close_status
  )

#Write normalization function----
normalize <- function (x) {
  return((x - min(x))/ (max(x) - min(x)))
}

#Normalize the training and testing sets----

parish_training <- na.omit(parish_training)

parish_train_norm <- as.data.frame(lapply(parish_training, normalize))

parish_testing <- na.omit(parish_testing)

parish_test_norm <- as.data.frame(lapply(parish_testing, normalize))

#View the normalized data----

summary(parish_train_norm)
summary(parish_test_norm)

#Building the model----

parish_model <- neuralnet(close_status ~  pledge17 + totrev17 + endow17 + totexp17 + commun17 + ssenr17 + worsh17 + easter17 + 
                            pledge16 + totrev16 + totexp16 + commun16 + ssenr16 + worsh16 + easter16 + 
                            pledge15 + totrev15 + totexp15 + commun15 + ssenr16 + worsh15 + easter15 + 
                            pledge13 + totrev13 + totexp13 + memb13 + ssenr13 + easter13 + 
                            pledge10 + totrev10 + totexp10 + memb10 + ssenr10 + easter10 + 
                            pledge09 + totrev09 + totexp09 + memb09 + ssenr09 + easter09 + worsh09 + 
                            pledge08 + totrev08 + totexp08 + memb08 + ssenr08 + easter08 + worsh08 + 
                            pledge07 + totrev07 + totexp07 + memb07 + ssenr07 + easter07 + worsh07 + 
                            pledge06 + totrev06 + totexp06 + memb06 + ssenr06 + easter06 + worsh06 + 
                            pledge05 + totrev05 + totexp05 + memb05 + ssenr05 + easter05 + worsh05 + 
                            TSEGNUM + TLIFECODE,
                          data = parish_train_norm, hidden = 1)

#Visualize the model----

plot(parish_model)

#Evaluating model performance----

model_test <- parish_test_norm %>% 
  select(., -close_status)

model_results <- compute(parish_model, model_test)

predicted_close_status <- model_results$net.result

cor(predicted_close_status, parish_test_norm$close_status)


#Using a softplus() activation function----

softplus <- function(x) {log(1 + exp(x))}


#Implement the softplus() function----

set.seed(12345)

parish_model2 <- neuralnet(close_status ~  pledge17 + totrev17 + endow17 + totexp17 + commun17 + ssenr17 + worsh17 + easter17 + 
                             pledge16 + totrev16 + totexp16 + commun16 + ssenr16 + worsh16 + easter16 + 
                             pledge15 + totrev15 + totexp15 + commun15 + ssenr16 + worsh15 + easter15 + 
                             pledge13 + totrev13 + totexp13 + memb13 + ssenr13 + easter13 + 
                             pledge10 + totrev10 + totexp10 + memb10 + ssenr10 + easter10 + 
                             pledge09 + totrev09 + totexp09 + memb09 + ssenr09 + easter09 + worsh09 + 
                             pledge08 + totrev08 + totexp08 + memb08 + ssenr08 + easter08 + worsh08 + 
                             pledge07 + totrev07 + totexp07 + memb07 + ssenr07 + easter07 + worsh07 + 
                             pledge06 + totrev06 + totexp06 + memb06 + ssenr06 + easter06 + worsh06 + 
                             pledge05 + totrev05 + totexp05 + memb05 + ssenr05 + easter05 + worsh05 + 
                             TSEGNUM + TLIFECODE,
                           data = parish_train_norm, 
                           hidden = c(2,2),
                           act.fct = softplus)

#Visualize the softplus model----

plot(parish_model2)

#Evaluating model performance----

model_test2 <- parish_test_norm %>% 
  select(., -close_status)

model_results2 <- compute(parish_model, model_test2)

predicted_close_status2 <- model_results2$net.result

cor(predicted_close_status2, parish_test_norm$close_status)

#Inspecting the predictions----

close_statuses <- data.frame(
  actual = parish_test_norm$close_status,
  pred = predicted_close_status2
)

#Function to denormalize the results----

denormalize <- function(x) {
  return((x * (max(x)) - min(x)) + min(x))
}

#Apply function to predictions----

close_statuses$pred_new <- denormalize(close_statuses$pred)

close_statuses$error <- close_statuses$pred_new - close_statuses$actual

head(close_statuses, n = 20)

cor(close_statuses$pred_new, close_statuses$actual)
